/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CircularNav: typeof import('./src/components/CircularNav.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    LingIntro: typeof import('./src/components/LingIntro.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RightMenu: typeof import('./src/components/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
