/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartBubble: typeof import('./src/components/charts/ChartBubble.vue')['default']
    ChartCircle: typeof import('./src/components/charts/ChartCircle.vue')['default']
    ChartRank: typeof import('./src/components/charts/ChartRank.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBackTop: typeof import('./src/components/TheBackTop.vue')['default']
    TheCircularNav: typeof import('./src/components/TheCircularNav.vue')['default']
    TheRightMenu: typeof import('./src/components/TheRightMenu.vue')['default']
  }
}
