/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartBubble: typeof import('./src/components/charts/ChartBubble.vue')['default']
    ChartCalendar: typeof import('./src/components/charts/ChartCalendar.vue')['default']
    ChartCircle: typeof import('./src/components/charts/ChartCircle.vue')['default']
    ChartHistogram: typeof import('./src/components/charts/ChartHistogram.vue')['default']
    ChartLine: typeof import('./src/components/charts/ChartLine.vue')['default']
    ChartPie: typeof import('./src/components/charts/ChartPie.vue')['default']
    ChartRadar: typeof import('./src/components/charts/ChartRadar.vue')['default']
    ChartRank: typeof import('./src/components/charts/ChartRank.vue')['default']
    ChartTranspose: typeof import('./src/components/charts/ChartTranspose.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    MapContainer: typeof import('./src/components/MapContainer.vue')['default']
    MobilePage: typeof import('./src/components/MobilePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBackTop: typeof import('./src/components/TheBackTop.vue')['default']
    TheCircularNav: typeof import('./src/components/TheCircularNav.vue')['default']
    TheRightMenu: typeof import('./src/components/TheRightMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
